#!/usr/bin/env python3
"""
KDCN — generate database/seeds/001_catalog.sql from catalog.csv + tiers.csv.
"""

import csv
from pathlib import Path

ROOT     = Path(__file__).parent.parent.resolve()
CATALOG  = ROOT / "assets" / "services" / "catalog.csv"
TIERS    = ROOT / "assets" / "services" / "tiers.csv"
OUT      = ROOT / "database" / "seeds" / "001_catalog.sql"

def sql(v):
    if v in (None, ""): return "NULL"
    return "'" + str(v).replace("'", "''") + "'"

def sqli(v):
    return "NULL" if v in (None, "") else str(int(v))

def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- AUTO-GENERATED by scripts/generate-catalog-seed.py",
        "-- Sources: assets/services/tiers.csv, assets/services/catalog.csv",
        "-- DO NOT EDIT. Regenerate instead.",
        "",
        "BEGIN TRANSACTION;",
        "",
        "-- tiers",
    ]
    with open(TIERS, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            lines.append(
                "INSERT OR REPLACE INTO tiers "
                "(id,name,icon,color,tagline,description,ideal_for,price_range,position) VALUES ("
                f"{sql(r['id'])},{sql(r['name'])},{sql(r['icon'])},{sql(r['color'])},"
                f"{sql(r['tagline'])},{sql(r['description'])},{sql(r['ideal_for'])},"
                f"{sql(r['price_range'])},{int(r['position'])});"
            )
    lines.append("")
    lines.append("-- services")

    with open(CATALOG, newline="", encoding="utf-8") as f:
        catalog_rows = list(csv.DictReader(f))
    for r in catalog_rows:
        active = "1" if r["active"].lower() == "true" else "0"
        lines.append(
            "INSERT OR REPLACE INTO services "
            "(svc_id,code,slug,tier,name,tagline,pricing_type,currency,"
            " price_min,price_max,price_display,ideal_for,objective,"
            " whatsapp_message,image_path,badge,active) VALUES ("
            f"{sql(r['svc_id'])},{sql(r['code'])},{sql(r['slug'])},{sql(r['tier'])},"
            f"{sql(r['name'])},{sql(r['tagline'])},{sql(r['pricing_type'])},{sql(r['currency'])},"
            f"{sqli(r['price_min'])},{sqli(r['price_max'])},{sql(r['price_display'])},"
            f"{sql(r['ideal_for'])},{sql(r['objective'])},{sql(r['whatsapp'])},"
            f"{sql(r['image'])},{sql(r['badge'])},{active});"
        )
    lines.append("")
    lines.append("-- service_includes")
    for r in catalog_rows:
        for idx, item in enumerate([i for i in r["includes"].split("|") if i.strip()], 1):
            lines.append(
                "INSERT OR REPLACE INTO service_includes "
                "(service_svc_id,position,item) VALUES "
                f"({sql(r['svc_id'])},{idx},{sql(item)});"
            )
    lines += ["", "COMMIT;", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ {OUT} ({len(catalog_rows)} services)")

if __name__ == "__main__":
    main()
